# Generated by Django 4.1.3 on 2022-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockquestionsmodel",
            name="description",
            field=models.CharField(default="some description", max_length=300),
            preserve_default=False,
        ),
    ]
