# Generated by Django 4.1.3 on 2022-12-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_rename_is_valid_answer_is_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="cat",
        ),
    ]
