# Generated by Django 4.1.3 on 2022-12-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_remove_question_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="questions.category",
                    ),
                ),
                ("questions", models.ManyToManyField(to="questions.question")),
            ],
        ),
    ]
