# Generated by Django 4.1.3 on 2022-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_blockquestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockquestions",
            name="name_block",
            field=models.CharField(default="some_name", max_length=63),
            preserve_default=False,
        ),
    ]
