# Generated by Django 4.1.3 on 2022-12-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_blockquestions_name_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="questions.category",
            ),
            preserve_default=False,
        ),
    ]
