# Generated by Django 4.1.3 on 2022-12-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_question_cat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlockQuestions",
            new_name="BlockQuestionsModel",
        ),
    ]
